### ISSUE TITLE
NaturalQuestions processor problem

### ISSUE THREAD

**Issue by laifuchicago** [deepset-ai/FARM#402] opened 2020-06-05 08:34 UTC
To: author
I use the NaturalLanguage processor , the training data comes from Google, link: https://ai.google.com/research/NaturalQuestions/download
 but the Farm can not train with the dataset, and the problem is shown below
![FarmProb](https://user-images.githubusercontent.com/8537280/83855222-585b0500-a74a-11ea-9e76-5ed10f8b966a.PNG)

Can you give me some idea, Thank you.
Jonathan
**Additional context**
Add any other context or screenshots about the question (optional).

**Comment by Timoeller** [comment] 2020-06-05 09:45
Hey @laifuchicago, happy to have people use our newest NQ functionality.
Looking at your stack trace it seems FARM starts to read in the data but has some encoding issues on the way.

Did you try with the given sample datasets and are they in the same format as the data you downloaded? Can you also verify the integrity of the train dataset with checksums?

Another thing that we realized during NQ data processing. It need quite some RAM, I guess about 200GB for the whole trainset. We will improve upon this in the future. Could this be related to your problem?

**Comment by laifuchicago** [comment] 2020-06-08 00:56
To author:
Thank you for answering, your sample data can work, when I first saw Natural question processor, I thought it was Google's Natural Questions just as the following link. The format is not the same.
https://ai.google.com/research/NaturalQuestions/download

Jonathan Sung

**Comment by Timoeller** [comment] 2020-06-08 11:51
Thanks for getting back, the format should be the simplified version of the dataset.

I ran the prcessing with the 17.5GB file "simplified-nq-train.jsonl". This dataset also forms the basis of the trained model that we uploaded, for its usage, see [here](https://github.com/deepset-ai/FARM/blob/master/examples/natural_questions.py#L126) and the following lines.

**Comment by laifuchicago** [comment] 2020-06-09 01:41
To author:
Actually, I used the simplified-nq-train.jsonl and dev file, when it processed to 9%, it showed the error, I have also checked the RAM in my server, it has enough RAM. I used the Roberta-Base model which you post.
![FarmProb2](https://user-images.githubusercontent.com/8537280/84096725-3658cf80-aa35-11ea-95af-c33330e2e7e8.PNG)
![FarmProb3](https://user-images.githubusercontent.com/8537280/84096727-3789fc80-aa35-11ea-8608-78928347dfc8.PNG)
Jonathan Sung

**Comment by Timoeller** [comment] 2020-06-09 08:59
Interesting. Do you know why your filename "v1.0-simplified_simplified-nq-train-jsonl" differs from ours? Did you do some preprocessing on the file yourself?

About downloading the NQ dataset from the google site - for some reason it is extremely difficult to just simply download the data (our accounts are blocked and you need a google account for access). It might be we have an older version of "simplified-nq-train.jsonl".

Could you post the full code of your script? The MaybeEncoding runtime error you are getting is quite weird... : )

**Comment by Timoeller** [comment] 2020-06-09 15:52
I found this [bug report](https://github.com/pytorch/pytorch/issues/2926) for pytorch on "RuntimeError: unable to write to file" stating it seems to be shared memory related.
You could try reducing the number of workers in out data_silo with parameter max_processes and see if it helps.

**Comment by laifuchicago** [comment] 2020-06-10 03:35
To Author:
 The figures below are my full code
![FarmProb2](https://user-images.githubusercontent.com/8537280/84224190-6fb13e00-ab0e-11ea-921f-9055a1ba3aa5.PNG)
![FarmProb3](https://user-images.githubusercontent.com/8537280/84224191-717b0180-ab0e-11ea-95bd-97623524c6c7.PNG)
![FarmProb4](https://user-images.githubusercontent.com/8537280/84224192-717b0180-ab0e-11ea-9da0-8c2869745fc3.PNG)
![FarmProb5](https://user-images.githubusercontent.com/8537280/84224196-72139800-ab0e-11ea-9d76-f76a302d9132.PNG)
![FarmProb6](https://user-images.githubusercontent.com/8537280/84224197-72139800-ab0e-11ea-8913-7d1735663f40.PNG)

Jonathan Sung

**Comment by Timoeller** [comment] 2020-06-10 08:45
The code you posted looks good on first sight.

I still suspect it is a memory issue. Also judging this [bug report](https://github.com/pytorch/pytorch/issues/2926) for pytorch on "RuntimeError: unable to write to file" that links the error to OOM. 
How much RAM does your server have and how many processes are spun up during data processing? I need above 200GB! RAM when converting the dataset. 
Can you see RAM usage going up during processing and by how much?

**Comment by laifuchicago** [comment] 2020-06-10 09:14
To Author:
The following figure is the Ram that I used. Before the training it was 396GB , During the training, it was 347GB. It use 50GB RAM. But still have over 300GB. That's a little bit weird.
![FarmProb7](https://user-images.githubusercontent.com/8537280/84249528-7905cf00-ab3d-11ea-8bad-0151ce3757fd.PNG)
![FarmProb8](https://user-images.githubusercontent.com/8537280/84249530-799e6580-ab3d-11ea-894a-e48b7329a535.PNG)

Jonathan Sung

**Comment by laifuchicago** [comment] 2020-06-17 08:30
To Author:
Do you have any suggestions? Thank you.
Jonathan Sung

**Comment by Timoeller** [comment] 2020-06-17 09:00
I know it is a bit frustrating.
Because I cannot reproduce the bug and the error message points to OOM issues related to pytorch (and not something inside FARM), I have difficulties in helping you. 

You said our example data runs through. If it is not OOM related, it might be that the datasets are different. You are using "v1.0-simplified_simplified-nq-train.jsonl". At least the name suggest it might be a different dataset.
Here is the md5 checksum of our training data: b2a27e6151e96d92086cbe02c013e9aa  simplified-nq-train.jsonl



------------
I can ping you again once we implement the next iteartion of Natural Questions, since right now this functionality is in beta mode.

**Comment by Timoeller** [comment] 2020-07-27 10:09
Sorry for not having a 100% satisfying solution. We also refactored a lot of NQ code. Maybe the problem does not persit any longer?
Closing this for now. Feel free to reopen.

**Closed by Timoeller** 2020-07-27 10:09 UTC
Labels: question
